[package]
name = "bevy-pyo3-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bevy_pyo3_test"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.100"
bevy = { version = "0.17", default-features = false, features = [
  # "std",
  # "animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_gltf",
  # "bevy_input_focus",
  "bevy_log",
  "bevy_mesh_picking_backend",
  "bevy_pbr",
  "bevy_picking",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_sprite_picking_backend",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "bevy_ui_picking_backend",
  "bevy_post_process",
  "default_font",
  "hdr",
  "multi_threaded",
  "png",
  "smaa_luts",
  "sysinfo_plugin",
  "tonemapping_luts",
  "vorbis",
  "zstd_rust",
] }
# bevy_platform_support = { version = "0.17",  default-features = false }
# bevy_internal = { version = "0.17.2", default-features = false }
bincode = { version = "2.0.1", features = ["serde"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel", "nightly"] }
image = { version = "0.25.8", features = ["serde"] }
linuxfb = "0.3.1"
noise = { version = "0.9.0", features = ["std"] }
# pyo3 = "0.26"
rand = { version = "0.9.2", features = ["nightly"] }
# vulkan-bevy-renderer = { git = "https://github.com/calacuda/flo", version = "0.1.0" }
